define ['sinon-qunit'], () ->
  -> 
    # TODO: use a class
    server = sinon.fakeServer.create()
    server.autoRespond = true
    # server.autoRespondAfter = 0
    server.respondWith '/api/v1/courses/1/modules.json', [
      200,
        'Content-Type': 'application/json'
        'Link': '<http://localhost:3000/api/v1/courses/1/modules?page=1&per_page=10>; rel="current",<http://localhost:3000/api/v1/courses/1/modules?page=2&per_page=10>; rel="next",<http://localhost:3000/api/v1/courses/1/modules?page=1&per_page=10>; rel="first",<http://localhost:3000/api/v1/courses/1/modules?page=21&per_page=10>; rel="last"'
      'while(1);[{"id":1,"name":"Test 1","position":1,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":2,"items_url":"http://localhost:3000/api/v1/courses/1/modules/1/items"},{"id":2,"name":"Test 2","position":2,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":1,"items_url":"http://localhost:3000/api/v1/courses/1/modules/2/items"},{"id":3,"name":"Module0","position":3,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/3/items"},{"id":4,"name":"Module1","position":4,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/4/items"},{"id":5,"name":"Module2","position":5,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/5/items"},{"id":6,"name":"Module3","position":6,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/6/items"},{"id":7,"name":"Module4","position":7,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/7/items"},{"id":8,"name":"Module5","position":8,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/8/items"},{"id":9,"name":"Module6","position":9,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/9/items"},{"id":10,"name":"Module7","position":10,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/10/items"}]'
    ]
    server.respondWith 'http://localhost:3000/api/v1/courses/1/modules?page=2&per_page=10', [
      200
      'Content-Type': 'application/json'
      'while(1);[{"id":11,"name":"Module8","position":11,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/11/items"},{"id":12,"name":"Module9","position":12,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/12/items"},{"id":13,"name":"Module10","position":13,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/13/items"},{"id":14,"name":"Module11","position":14,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/14/items"},{"id":15,"name":"Module12","position":15,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/15/items"},{"id":16,"name":"Module13","position":16,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/16/items"},{"id":17,"name":"Module14","position":17,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/17/items"},{"id":18,"name":"Module15","position":18,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/18/items"},{"id":19,"name":"Module16","position":19,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/19/items"},{"id":20,"name":"Module17","position":20,"unlock_at":null,"require_sequential_progress":false,"prerequisite_module_ids":[],"published":true,"items_count":0,"items_url":"http://localhost:3000/api/v1/courses/1/modules/20/items"}]'
    ]

    server
